
development:
  adapter: postgresql
  encoding: unicode
  database: rails_api_only_jwt_example_dev
  pool: 5
  username: colemerrick
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: rails_api_only_jwt_example_dev
  pool: 5
  username: colemerrick
  password:
