# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e0050f42c728b2cd13caec389efa8ffcd17a0ed94e008004b72f4a09b8c9007ccb1c4a0c10fc603be2ce3c2df452242d06afb09663505c2f1bc75ecf9bbc4cad

test:
  secret_key_base: dcb0c3804cb83c09dedba8d4deae132099b0e718c45dd07cf4b5f2ac58c96983f4990331664b6ae7dd97c755042fc5e9b69ffbae3e5edefc0489ab7c313b6ce0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
